# Generated by Django 2.2.3 on 2019-08-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('Registration_ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('MobileNo', models.IntegerField()),
                ('Password', models.CharField(max_length=255)),
                ('Created_Date', models.DateTimeField(auto_now_add=True)),
                ('Updated_Date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Registration',
            },
        ),
        migrations.CreateModel(
            name='Registration_OTP',
            fields=[
                ('Registration_OTP_ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=50)),
                ('otp', models.IntegerField()),
            ],
            options={
                'db_table': 'Registration_OTP',
            },
        ),
    ]
