# Generated by Django 2.2.3 on 2019-08-30 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatting',
            fields=[
                ('Chatting_Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Message', models.TextField(max_length=5000)),
                ('Created_Date', models.DateTimeField(auto_now_add=True)),
                ('Registration_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Registration')),
            ],
        ),
    ]
