# Generated by Django 2.2.3 on 2019-08-30 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_chatting'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatting',
            table='Chatting',
        ),
    ]
