# Generated by Django 2.2.3 on 2019-08-31 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20190830_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatting',
            name='Created_Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
