# Generated by Django 2.2.3 on 2019-09-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_registration_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Profile_Photo',
            field=models.ImageField(default='Profile_Photos/User_Profile.png', upload_to='Profile_Photos/'),
        ),
    ]
